VENDOR=Cisco
NAME=Nexus9000v
IMAGE_FORMAT=qcow2
IMAGE_GLOB=*.qcow2

# match versions like:
VERSION=$(shell echo $(IMAGE) | grep -oE "\b[0-9].\b[0-9].\b[0-9]")

-include ../makefile-sanity.include
-include ../makefile.include
